// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ivkcyrpwgangohnccbqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Iml2a2N5cnB3Z2FuZ29obmNjYnF3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ0NTc3NTcsImV4cCI6MjA3MDAzMzc1N30.yeLQ0a5ip1Q_mgxhc3I7NhFzjAiLj2EVopMIKGnvKxM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});